version: "3.8"
services:
  postgres:
    image: postgres
    container_name: file-sharing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file-sharing-api
